#!/usr/bin/env node
// DeepRead 精读助手 — client 构建脚本。
// 将 src/client/index.js（工厂包体）包装成 C6 工厂包产物：
//   window.__ModuleLoader__.load({ id, factory: (require) => ... })
// 与官方 tsdown clientBundle 产物同构：工厂内 var module/exports 前导 +
// Object.defineProperty(Symbol.toStringTag) + return module.exports。
// lib/client.js 是生成产物，勿手改；source of truth 是 src/client/index.js。
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const ID = 'dsh-deepread'
const source = readFileSync(join(root, 'src/client/index.js'), 'utf8')

const bundle = [
  '/* DeepRead 精读助手 — client bundle (C6 factory). Generated by scripts/build-client.mjs — do not edit by hand. */',
  'window.__ModuleLoader__.load({',
  '  id: ' + JSON.stringify(ID) + ',',
  '  factory: (require) => {',
  '    var module = { exports: {} };',
  '    var exports = module.exports;',
  "    Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });",
  source.trimEnd(),
  '',
  '    return module.exports;',
  '  },',
  '});',
  '',
].join('\n')

mkdirSync(join(root, 'lib'), { recursive: true })
const out = join(root, 'lib/client.js')
writeFileSync(out, bundle)
console.log('built', out, `(${Buffer.byteLength(bundle)} bytes)`)
